
server:
  port: 2000
eureka:
  instance:
    instance-id: userservice
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8260/eureka/  # 注册中心访问地址
spring:
  application:
    name: userservice